apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-agent-sample

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ai-agent-sample
    newName: ai-agent-sample
    newTag: local-20260825

configMapGenerator:
  - name: ai-agent-sample-config
    behavior: merge
    literals:
      - ENVIRONMENT=local
      - AGENT_COMMAND_ENABLED=true

secretGenerator:
  - name: ai-agent-sample-secrets
    envs:
      - secrets.env

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ai-agent-sample
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
