apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-agent-sample-secrets
  labels:
    app.kubernetes.io/name: ai-agent-sample
    app.kubernetes.io/component: secret-store
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: ai-agent-sample-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DP_API_KEY
      remoteRef:
        key: eks-workshop/dev/ai-agent-sample
        property: DP_API_KEY
    - secretKey: API_BEARER_TOKEN
      remoteRef:
        key: eks-workshop/dev/ai-agent-sample
        property: API_BEARER_TOKEN
